name: Deploy Firebase Functions

on:
  push:
    branches: [main]
    paths:
      - "lib/firebase/cloud-functions/**"

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd lib/firebase/cloud-functions
          npm ci

      - name: Deploy to Firebase
        run: |
          cd lib/firebase/cloud-functions
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
